### ISSUE TITLE
Can this be used to fuzz DTLS protocol? Can I get the input list ?

### ISSUE THREAD

**Issue by purninavi** [denandz/fuzzotron#14]

**Comment by denandz** [comment]
I've just added DTLS support with 0f0449dbad5e1ab103c6ddf5f656d5dfd74ece98. It's pretty experimental still, so let me know how it goes for you. You should run fuzzotron with something like `./fuzzotron --radamsa --directory testcases -o output -h 127.0.0.1 -p8181 -P udp --ssl`.

Unless you wanted to fuzz the DTLS protocol itself, rather than whatever was using DTLS? In which case leave off the `--ssl`.

**Comment by denandz** [comment]
Closed by 0f0449d
