### ISSUE TITLE
QUIC Support

### ISSUE THREAD

**Issue by Karthikdasari0423** [denandz/fuzzotron#17]
@denandz is there any plan to support QUIC protocol also fuzzing also in near ?

**Comment by denandz** [comment]
Fuzzotron doesn't understand specific protocols and operates one layer below QUIC (UDP, in this case). You could likely fuzz the QUIC protocol by grabbing the packets that you want to fuzz and writing any initial setup logic into `callback.c` before sending your target packet. This will... probably be hard. Especially with the various TLS things going on as part of QUIC.

Maybe a better option would be to look at modifying an existing QUIC client to fuzz the various packets as they're getting sent, rather than implement QUIC from scratch in Fuzzotron? Theres a good write up from Natalie Silvanovich on doing something similar with WebRTC here: https://googleprojectzero.blogspot.com/2018/12/adventures-in-video-conferencing-part-1.html Might be a quicker win.

**Comment by Karthikdasari0423** [comment]
okay,Thank @denandz
